<?php

declare(strict_types=1);

namespace App\Models;

use App\Enums\GameSessionSource;
use App\Enums\SessionDetectionSource;
use App\Enums\SessionEndReason;
use Carbon\CarbonInterface;
use Database\Factories\GameSessionFactory;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Override;

/**
 * A measured play session. The id is generated by the Companion so every snapshot is idempotent.
 *
 * @property string $id
 * @property string $user_id
 * @property int $game_id
 * @property int|null $companion_device_id
 * @property int|null $game_executable_mapping_id
 * @property GameSessionSource $source
 * @property SessionDetectionSource $detection_source
 * @property CarbonInterface $started_at
 * @property CarbonInterface $last_heartbeat_at
 * @property CarbonInterface|null $ended_at
 * @property int $active_seconds
 * @property int $idle_seconds
 * @property SessionEndReason|null $end_reason
 * @property CarbonInterface|null $effects_applied_at
 * @property CarbonInterface $created_at
 * @property CarbonInterface $updated_at
 */
final class GameSession extends Model
{
    /** @use HasFactory<GameSessionFactory> */
    use HasFactory;

    use HasUuids;

    /**
     * @var list<string>
     */
    #[Override]
    protected $fillable = [
        'id',
        'user_id',
        'game_id',
        'companion_device_id',
        'game_executable_mapping_id',
        'source',
        'detection_source',
        'started_at',
        'last_heartbeat_at',
        'ended_at',
        'active_seconds',
        'idle_seconds',
        'end_reason',
        'effects_applied_at',
    ];

    /**
     * @return array<string, string>
     */
    public function casts(): array
    {
        return [
            'source' => GameSessionSource::class,
            'detection_source' => SessionDetectionSource::class,
            'started_at' => 'datetime',
            'last_heartbeat_at' => 'datetime',
            'ended_at' => 'datetime',
            'active_seconds' => 'integer',
            'idle_seconds' => 'integer',
            'end_reason' => SessionEndReason::class,
            'effects_applied_at' => 'datetime',
        ];
    }

    /**
     * @return BelongsTo<Game, $this>
     */
    public function game(): BelongsTo
    {
        return $this->belongsTo(Game::class);
    }

    /**
     * @param  Builder<GameSession>  $query
     * @return Builder<GameSession>
     */
    public function scopeOpen(Builder $query): Builder
    {
        return $query->whereNull('ended_at');
    }

    /**
     * Closed by its device: later snapshots can no longer change it.
     */
    public function isFinal(): bool
    {
        return $this->ended_at !== null && $this->end_reason?->isServerSide() !== true;
    }

    /**
     * Closes the session at its last heartbeat, for a reason decided by the server.
     */
    public function closeAtLastHeartbeat(SessionEndReason $reason): void
    {
        $this->forceFill([
            'ended_at' => $this->last_heartbeat_at,
            'end_reason' => $reason,
        ])->save();
    }
}
