<?php

declare(strict_types=1);

namespace App\Models;

use Carbon\CarbonInterface;
use Database\Factories\SavedMomentFactory;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Override;

/**
 * A screenshot saved from a game with the Companion shortcut (fiche A6). The id is generated by the Companion so
 * every upload is idempotent. Images live on a private disk and are only served to their owner.
 *
 * @property string $id
 * @property string $user_id
 * @property int $game_id
 * @property string $game_session_id
 * @property int|null $companion_device_id
 * @property CarbonInterface $captured_at
 * @property string $disk
 * @property string $path
 * @property string|null $thumbnail_path
 * @property int $width
 * @property int $height
 * @property int $size_bytes
 * @property string|null $caption
 * @property CarbonInterface $created_at
 * @property CarbonInterface $updated_at
 */
final class SavedMoment extends Model
{
    /** @use HasFactory<SavedMomentFactory> */
    use HasFactory;

    use HasUuids;

    public const int CAPTION_MAX_LENGTH = 280;

    /**
     * @var list<string>
     */
    #[Override]
    protected $fillable = [
        'id',
        'user_id',
        'game_id',
        'game_session_id',
        'companion_device_id',
        'captured_at',
        'disk',
        'path',
        'thumbnail_path',
        'width',
        'height',
        'size_bytes',
        'caption',
    ];

    /**
     * @return array<string, string>
     */
    public function casts(): array
    {
        return [
            'captured_at' => 'datetime',
            'width' => 'integer',
            'height' => 'integer',
            'size_bytes' => 'integer',
        ];
    }

    /**
     * @return BelongsTo<User, $this>
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    /**
     * @return BelongsTo<Game, $this>
     */
    public function game(): BelongsTo
    {
        return $this->belongsTo(Game::class);
    }

    /**
     * @return BelongsTo<GameSession, $this>
     */
    public function session(): BelongsTo
    {
        return $this->belongsTo(GameSession::class, 'game_session_id');
    }

    /**
     * @return BelongsTo<CompanionDevice, $this>
     */
    public function device(): BelongsTo
    {
        return $this->belongsTo(CompanionDevice::class, 'companion_device_id');
    }
}
